
/* Drop Tables */

DROP TABLE BBS CASCADE CONSTRAINTS;
DROP TABLE CMMN_CODE CASCADE CONSTRAINTS;
DROP TABLE COIN_REPOSITORY CASCADE CONSTRAINTS;
DROP TABLE COIN_REPOSITORY_HIST CASCADE CONSTRAINTS;
DROP TABLE MNGR_INQRY CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE REFND CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE SETLE CASCADE CONSTRAINTS;
DROP TABLE RESVE CASCADE CONSTRAINTS;
DROP TABLE SELER_IMAGE CASCADE CONSTRAINTS;
DROP TABLE TAG_SEARCH CASCADE CONSTRAINTS;
DROP TABLE VOCHR CASCADE CONSTRAINTS;
DROP TABLE SELER CASCADE CONSTRAINTS;
DROP TABLE WALLET_DTLS CASCADE CONSTRAINTS;
DROP TABLE WALLET CASCADE CONSTRAINTS;
DROP TABLE MBER CASCADE CONSTRAINTS;
DROP TABLE REFND_HIST CASCADE CONSTRAINTS;
DROP TABLE RESVE_SETLE_HIST CASCADE CONSTRAINTS;
DROP TABLE TAG_READ_CNT CASCADE CONSTRAINTS;
DROP TABLE TAG CASCADE CONSTRAINTS;
DROP TABLE VOCHR_HIST CASCADE CONSTRAINTS;
DROP TABLE WALLET_DTLS_HIST CASCADE CONSTRAINTS;




/* Create Tables */

-- 자유게시판
CREATE TABLE BBS
(
	-- 게시글 번호
	BBSCTT_NO varchar2(4) NOT NULL,
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 상위 게시글 번호
	UP_BBSCTT_NO varchar2(4),
	-- 게시글 제목
	BBSCTT_SJ varchar2(90),
	-- 게시글 내용
	BBSCTT_CN varchar2(300),
	-- 작성 일시
	BBSCTT_DT date,
	PRIMARY KEY (BBSCTT_NO)
);


-- 공통 코드
CREATE TABLE CMMN_CODE
(
	-- 공통 코드
	CMMN_CODE varchar2(4) NOT NULL,
	-- 코드명
	CODE_NM varchar2(100),
	PRIMARY KEY (CMMN_CODE)
);


-- 코인 저장소
CREATE TABLE COIN_REPOSITORY
(
	-- 거래 코드
	DELNG_CODE varchar2(6) NOT NULL,
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 결제 코드
	SETLE_CODE varchar2(4) NOT NULL,
	-- 거래 일시
	DELNG_DT timestamp NOT NULL,
	-- 거래 분류
	DELNG_SE char NOT NULL,
	-- 거래 금액
	DELNG_AMOUNT number NOT NULL,
	-- 저장 코인 수
	REPOSITORY_COIN_CO number NOT NULL,
	PRIMARY KEY (DELNG_CODE)
);


-- 코인 저장소 이력
CREATE TABLE COIN_REPOSITORY_HIST
(
	-- 기록 일시
	RCORD_DT timestamp NOT NULL,
	-- 이력 구분
	HIST_SE varchar2(20) NOT NULL,
	-- 거래 코드
	DELNG_CODE varchar2(6),
	-- 회원 코드
	MBER_CODE varchar2(4),
	-- 결제 코드
	SETLE_CODE varchar2(4),
	-- 거래 일시
	DELNG_DT timestamp,
	-- 거래 분류
	DELNG_SE char,
	-- 거래 금액
	DELNG_AMOUNT number,
	-- 저장 코인 수
	REPOSITORY_COIN_CO number,
	PRIMARY KEY (RCORD_DT)
);


-- 회원
CREATE TABLE MBER
(
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 회원 아이디
	MBER_ID varchar2(20) NOT NULL UNIQUE,
	-- 회원 패스워드
	MBER_PW varchar2(20) NOT NULL,
	-- 회원 실명
	MBER_RLNM varchar2(21) NOT NULL,
	-- 은행 코드
	BANK_CODE varchar2(4),
	-- 회원 계좌번호
	MBER_ACOUNTNO varchar2(15),
	-- 회원 이메일
	MBER_EMAIL varchar2(30) NOT NULL UNIQUE,
	-- 회원 닉네임
	MBER_NCNM varchar2(30) NOT NULL UNIQUE,
	-- 회원 전화번호
	MBER_TEL varchar2(13),
	-- 회원 생년월일
	MBER_BRTHDY varchar2(8),
	-- 회원 권한 레벨
	MBER_AUTHOR_LEVEL char NOT NULL,
	-- 가입일
	SRBDE varchar2(8) NOT NULL,
	-- 회원 탈퇴 여부
	MBER_SECSN_AT char NOT NULL,
	PRIMARY KEY (MBER_CODE)
);


-- 관리자 문의
CREATE TABLE MNGR_INQRY
(
	-- 관리자 문의 번호
	MNGR_INQRY_NO varchar2(4) NOT NULL,
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 관리자 답변 번호
	MNGR_ANSWER_NO varchar2(4),
	-- 문의 제목
	INQRY_SJ varchar2(90),
	-- 문의 내용
	INQRY_CN varchar2(300),
	-- 문의 일시
	INQRY_DT date,
	PRIMARY KEY (MNGR_INQRY_NO)
);


-- 공지
CREATE TABLE NOTICE
(
	-- 게시글 번호
	BBSCTT_NO varchar2(4) NOT NULL,
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 게시글 제목
	BBSCTT_SJ varchar2(90),
	-- 게시글 내용
	BBSCTT_CN varchar2(300),
	-- 작성 일시
	BBSCTT_DT date,
	PRIMARY KEY (BBSCTT_NO)
);


-- 환불
CREATE TABLE REFND
(
	-- 결제 코드
	SETLE_CODE varchar2(4) NOT NULL,
	-- 환불 금액
	REFND_PC number NOT NULL,
	-- 환불 일시
	REFND_DT date NOT NULL,
	-- 환불 완료 여부
	REFND_AT char,
	-- 환불 사유
	REFND_RESN varchar2(100) NOT NULL,
	PRIMARY KEY (SETLE_CODE)
);


-- 환불 이력
CREATE TABLE REFND_HIST
(
	-- 기록 일시
	RCORD_DT timestamp NOT NULL,
	-- 이력 구분
	HIST_SE varchar2(20) NOT NULL,
	-- 결제 코드
	SETLE_CODE varchar2(4),
	-- 환불 가격
	REFND_PC number,
	-- 환불 일시
	REFND_DT date,
	-- 환불 완료 여부
	REFND_AT char,
	-- 환불 사유
	REFND_RESN varchar2(100),
	PRIMARY KEY (RCORD_DT)
);


-- 예약
CREATE TABLE RESVE
(
	-- 예약 코드
	RESVE_CODE varchar2(4) NOT NULL,
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 식사권 코드
	VOCHR_CODE varchar2(4) NOT NULL,
	-- 예약 가격
	RESVE_PC number NOT NULL,
	-- 예약 일시
	RESVE_DT date NOT NULL,
	PRIMARY KEY (RESVE_CODE)
);


-- 예약 및 결제 이력
CREATE TABLE RESVE_SETLE_HIST
(
	-- 기록 일시
	RCORD_DT timestamp NOT NULL,
	-- 이력 구분
	HIST_SE varchar2(20) NOT NULL,
	-- 예약 또는 결제 코드
	RESVE_SETLE_CODE varchar2(4),
	-- 회원 코드
	MBER_CODE varchar2(4),
	-- 식사권 코드
	VOCHR_CODE varchar2(4),
	-- 예약 가격
	RESVE_PC number,
	-- 예약 일시
	RESVE_DT date,
	-- 결제 가격
	SETLE_PC number,
	-- 결제 일시
	SETLE_DT date,
	-- 결제 완료 여부
	SETLE_AT char,
	-- 환불 신청 여부
	REFND_REQST_AT char,
	-- 구매 확정 여부
	PURCHS_DCSN_AT char,
	PRIMARY KEY (RCORD_DT)
);


-- 리뷰
CREATE TABLE REVIEW
(
	-- 결제 코드
	SETLE_CODE varchar2(4) NOT NULL,
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 리뷰 내용
	REVIEW_CN varchar2(100),
	-- 리뷰 일자
	REVIEW_DATE date,
	PRIMARY KEY (SETLE_CODE)
);


-- 판매자
CREATE TABLE SELER
(
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 판매자 자기소개
	SELER_SELF_INTRCN varchar2(900),
	-- 판매자 경력사항
	SELER_CAREER varchar2(900),
	-- 판매자 학력사항
	SELER_ACDMCR varchar2(900),
	-- 판매자 명언
	SELER_APRSM varchar2(150),
	-- 판매자 거주지역
	SELER_RESDNC varchar2(300),
	-- 판매자 직업
	SELER_OCCP varchar2(90),
	-- 판매자 연령
	SELER_AGE number,
	PRIMARY KEY (MBER_CODE)
);


-- 판매자 이미지
CREATE TABLE SELER_IMAGE
(
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 등록순서
	SNO number NOT NULL,
	-- 이미지 경로
	IMAGE_ADRES varchar2(200),
	PRIMARY KEY (MBER_CODE, SNO)
);


-- 결제
CREATE TABLE SETLE
(
	-- 결제 코드
	SETLE_CODE varchar2(4) NOT NULL,
	-- 결제 가격
	SETLE_PC number NOT NULL,
	-- 결제 일시
	SETLE_DT date NOT NULL,
	-- 결제 완료 여부
	SETLE_AT char NOT NULL,
	-- 환불 신청 여부
	REFND_REQST_AT char,
	-- 구매 확정 여부
	PURCHS_DCSN_AT char NOT NULL,
	PRIMARY KEY (SETLE_CODE)
);


-- 태그
CREATE TABLE TAG
(
	-- 태그 코드
	TAG_CODE varchar2(4) NOT NULL,
	-- 태그명
	TAG_NM varchar2(30),
	-- 이미지 경로
	IMAGE_ADRES varchar2(200),
	PRIMARY KEY (TAG_CODE)
);


-- 태그 조회수
CREATE TABLE TAG_READ_CNT
(
	-- 태그 코드
	TAG_CODE varchar2(4) NOT NULL,
	-- 태그 조회수
	TAG_READ_CNT number,
	PRIMARY KEY (TAG_CODE)
);


-- 태그 검색
CREATE TABLE TAG_SEARCH
(
	-- 태그 코드
	TAG_CODE varchar2(4) NOT NULL,
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	PRIMARY KEY (TAG_CODE, MBER_CODE)
);


-- 식사권
CREATE TABLE VOCHR
(
	-- 식사권 코드
	VOCHR_CODE varchar2(4) NOT NULL,
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 식사권 가격
	VOCHR_PRICE number NOT NULL,
	-- 식사 예정 일시
	MEAL_PREARNGE_DT varchar2(12) NOT NULL,
	-- 식사권 등록 일시
	VOCHR_REGIST_DT date NOT NULL,
	-- 식사 시간
	MEAL_TIME number,
	-- 거래 가능 여부
	DELNG_AT char,
	PRIMARY KEY (VOCHR_CODE)
);


-- 식사권 이력
CREATE TABLE VOCHR_HIST
(
	-- 기록 일시
	RCORD_DT timestamp NOT NULL,
	-- 이력 구분
	HIST_SE varchar2(20) NOT NULL,
	-- 식사권 코드
	VOCHR_CODE varchar2(4),
	-- 회원 코드
	MBER_CODE varchar2(4),
	-- 식사권 가격
	VOCHR_PRICE number,
	-- 식사 예정 일시
	MEAL_PREARNGE_DT varchar2(12),
	-- 식사권 등록 일시
	VOCHR_REGIST_DT date,
	-- 식사 시간
	MEAL_TIME number,
	-- 거래 가능 여부
	DELNG_AT char,
	PRIMARY KEY (RCORD_DT)
);


-- 지갑
CREATE TABLE WALLET
(
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 코인 수
	COIN_CO number NOT NULL,
	PRIMARY KEY (MBER_CODE)
);


-- 지갑 내역
CREATE TABLE WALLET_DTLS
(
	-- 회원 코드
	MBER_CODE varchar2(4) NOT NULL,
	-- 입출금 일시
	RCPPAY_DT timestamp NOT NULL,
	-- 입출금 분류
	RCPPAY_CL char NOT NULL,
	-- 입출금 금액
	RCPPAY_AMOUNT number NOT NULL,
	-- 환전 코인 수
	EXCNG_COIN_CO number NOT NULL,
	PRIMARY KEY (MBER_CODE, RCPPAY_DT)
);


-- 지갑내역 이력
CREATE TABLE WALLET_DTLS_HIST
(
	-- 기록 일시
	RCORD_DT timestamp NOT NULL,
	-- 이력 구분
	HIST_SE varchar2(20) NOT NULL,
	-- 회원 코드
	MBER_CODE varchar2(4),
	-- 입출금 일자
	RCPPAY_DT timestamp,
	-- 입출금 분류
	RCPPAY_CL char NOT NULL,
	-- 입출금 금액
	RCPPAY_AMOUNT number NOT NULL,
	-- 환전 코인 수
	EXCNG_COIN_CO number NOT NULL,
	-- 코인 수
	COIN_CO number,
	PRIMARY KEY (RCORD_DT)
);



/* Create Foreign Keys */

ALTER TABLE BBS
	ADD FOREIGN KEY (UP_BBSCTT_NO)
	REFERENCES BBS (BBSCTT_NO)
;


ALTER TABLE BBS
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES MBER (MBER_CODE)
;


ALTER TABLE MNGR_INQRY
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES MBER (MBER_CODE)
;


ALTER TABLE NOTICE
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES MBER (MBER_CODE)
;


ALTER TABLE RESVE
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES MBER (MBER_CODE)
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES MBER (MBER_CODE)
;


ALTER TABLE SELER
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES MBER (MBER_CODE)
;


ALTER TABLE WALLET
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES MBER (MBER_CODE)
;


ALTER TABLE MNGR_INQRY
	ADD FOREIGN KEY (MNGR_ANSWER_NO)
	REFERENCES MNGR_INQRY (MNGR_INQRY_NO)
;


ALTER TABLE SETLE
	ADD FOREIGN KEY (SETLE_CODE)
	REFERENCES RESVE (RESVE_CODE)
;


ALTER TABLE SELER_IMAGE
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES SELER (MBER_CODE)
;


ALTER TABLE TAG_SEARCH
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES SELER (MBER_CODE)
;


ALTER TABLE VOCHR
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES SELER (MBER_CODE)
;


ALTER TABLE COIN_REPOSITORY
	ADD FOREIGN KEY (SETLE_CODE)
	REFERENCES SETLE (SETLE_CODE)
;


ALTER TABLE REFND
	ADD FOREIGN KEY (SETLE_CODE)
	REFERENCES SETLE (SETLE_CODE)
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (SETLE_CODE)
	REFERENCES SETLE (SETLE_CODE)
;


ALTER TABLE TAG_READ_CNT
	ADD FOREIGN KEY (TAG_CODE)
	REFERENCES TAG (TAG_CODE)
;


ALTER TABLE TAG_SEARCH
	ADD FOREIGN KEY (TAG_CODE)
	REFERENCES TAG (TAG_CODE)
;


ALTER TABLE RESVE
	ADD FOREIGN KEY (VOCHR_CODE)
	REFERENCES VOCHR (VOCHR_CODE)
;


ALTER TABLE COIN_REPOSITORY
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES WALLET (MBER_CODE)
;


ALTER TABLE WALLET_DTLS
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES WALLET (MBER_CODE)
;



/* Comments */

COMMENT ON TABLE BBS IS '자유게시판';
COMMENT ON COLUMN BBS.BBSCTT_NO IS '게시글 번호';
COMMENT ON COLUMN BBS.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN BBS.UP_BBSCTT_NO IS '상위 게시글 번호';
COMMENT ON COLUMN BBS.BBSCTT_SJ IS '게시글 제목';
COMMENT ON COLUMN BBS.BBSCTT_CN IS '게시글 내용';
COMMENT ON COLUMN BBS.BBSCTT_DT IS '작성 일시';
COMMENT ON TABLE CMMN_CODE IS '공통 코드';
COMMENT ON COLUMN CMMN_CODE.CMMN_CODE IS '공통 코드';
COMMENT ON COLUMN CMMN_CODE.CODE_NM IS '코드명';
COMMENT ON TABLE COIN_REPOSITORY IS '코인 저장소';
COMMENT ON COLUMN COIN_REPOSITORY.DELNG_CODE IS '거래 코드';
COMMENT ON COLUMN COIN_REPOSITORY.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN COIN_REPOSITORY.SETLE_CODE IS '결제 코드';
COMMENT ON COLUMN COIN_REPOSITORY.DELNG_DT IS '거래 일시';
COMMENT ON COLUMN COIN_REPOSITORY.DELNG_SE IS '거래 분류';
COMMENT ON COLUMN COIN_REPOSITORY.DELNG_AMOUNT IS '거래 금액';
COMMENT ON COLUMN COIN_REPOSITORY.REPOSITORY_COIN_CO IS '저장 코인 수';
COMMENT ON TABLE COIN_REPOSITORY_HIST IS '코인 저장소 이력';
COMMENT ON COLUMN COIN_REPOSITORY_HIST.RCORD_DT IS '기록 일시';
COMMENT ON COLUMN COIN_REPOSITORY_HIST.HIST_SE IS '이력 구분';
COMMENT ON COLUMN COIN_REPOSITORY_HIST.DELNG_CODE IS '거래 코드';
COMMENT ON COLUMN COIN_REPOSITORY_HIST.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN COIN_REPOSITORY_HIST.SETLE_CODE IS '결제 코드';
COMMENT ON COLUMN COIN_REPOSITORY_HIST.DELNG_DT IS '거래 일시';
COMMENT ON COLUMN COIN_REPOSITORY_HIST.DELNG_SE IS '거래 분류';
COMMENT ON COLUMN COIN_REPOSITORY_HIST.DELNG_AMOUNT IS '거래 금액';
COMMENT ON COLUMN COIN_REPOSITORY_HIST.REPOSITORY_COIN_CO IS '저장 코인 수';
COMMENT ON TABLE MBER IS '회원';
COMMENT ON COLUMN MBER.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN MBER.MBER_ID IS '회원 아이디';
COMMENT ON COLUMN MBER.MBER_PW IS '회원 패스워드';
COMMENT ON COLUMN MBER.MBER_RLNM IS '회원 실명';
COMMENT ON COLUMN MBER.BANK_CODE IS '은행 코드';
COMMENT ON COLUMN MBER.MBER_ACOUNTNO IS '회원 계좌번호';
COMMENT ON COLUMN MBER.MBER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN MBER.MBER_NCNM IS '회원 닉네임';
COMMENT ON COLUMN MBER.MBER_TEL IS '회원 전화번호';
COMMENT ON COLUMN MBER.MBER_BRTHDY IS '회원 생년월일';
COMMENT ON COLUMN MBER.MBER_AUTHOR_LEVEL IS '회원 권한 레벨';
COMMENT ON COLUMN MBER.SRBDE IS '가입일';
COMMENT ON COLUMN MBER.MBER_SECSN_AT IS '회원 탈퇴 여부';
COMMENT ON TABLE MNGR_INQRY IS '관리자 문의';
COMMENT ON COLUMN MNGR_INQRY.MNGR_INQRY_NO IS '관리자 문의 번호';
COMMENT ON COLUMN MNGR_INQRY.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN MNGR_INQRY.MNGR_ANSWER_NO IS '관리자 답변 번호';
COMMENT ON COLUMN MNGR_INQRY.INQRY_SJ IS '문의 제목';
COMMENT ON COLUMN MNGR_INQRY.INQRY_CN IS '문의 내용';
COMMENT ON COLUMN MNGR_INQRY.INQRY_DT IS '문의 일시';
COMMENT ON TABLE NOTICE IS '공지';
COMMENT ON COLUMN NOTICE.BBSCTT_NO IS '게시글 번호';
COMMENT ON COLUMN NOTICE.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN NOTICE.BBSCTT_SJ IS '게시글 제목';
COMMENT ON COLUMN NOTICE.BBSCTT_CN IS '게시글 내용';
COMMENT ON COLUMN NOTICE.BBSCTT_DT IS '작성 일시';
COMMENT ON TABLE REFND IS '환불';
COMMENT ON COLUMN REFND.SETLE_CODE IS '결제 코드';
COMMENT ON COLUMN REFND.REFND_PC IS '환불 금액';
COMMENT ON COLUMN REFND.REFND_DT IS '환불 일시';
COMMENT ON COLUMN REFND.REFND_AT IS '환불 완료 여부';
COMMENT ON COLUMN REFND.REFND_RESN IS '환불 사유';
COMMENT ON TABLE REFND_HIST IS '환불 이력';
COMMENT ON COLUMN REFND_HIST.RCORD_DT IS '기록 일시';
COMMENT ON COLUMN REFND_HIST.HIST_SE IS '이력 구분';
COMMENT ON COLUMN REFND_HIST.SETLE_CODE IS '결제 코드';
COMMENT ON COLUMN REFND_HIST.REFND_PC IS '환불 가격';
COMMENT ON COLUMN REFND_HIST.REFND_DT IS '환불 일시';
COMMENT ON COLUMN REFND_HIST.REFND_AT IS '환불 완료 여부';
COMMENT ON COLUMN REFND_HIST.REFND_RESN IS '환불 사유';
COMMENT ON TABLE RESVE IS '예약';
COMMENT ON COLUMN RESVE.RESVE_CODE IS '예약 코드';
COMMENT ON COLUMN RESVE.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN RESVE.VOCHR_CODE IS '식사권 코드';
COMMENT ON COLUMN RESVE.RESVE_PC IS '예약 가격';
COMMENT ON COLUMN RESVE.RESVE_DT IS '예약 일시';
COMMENT ON TABLE RESVE_SETLE_HIST IS '예약 및 결제 이력';
COMMENT ON COLUMN RESVE_SETLE_HIST.RCORD_DT IS '기록 일시';
COMMENT ON COLUMN RESVE_SETLE_HIST.HIST_SE IS '이력 구분';
COMMENT ON COLUMN RESVE_SETLE_HIST.RESVE_SETLE_CODE IS '예약 또는 결제 코드';
COMMENT ON COLUMN RESVE_SETLE_HIST.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN RESVE_SETLE_HIST.VOCHR_CODE IS '식사권 코드';
COMMENT ON COLUMN RESVE_SETLE_HIST.RESVE_PC IS '예약 가격';
COMMENT ON COLUMN RESVE_SETLE_HIST.RESVE_DT IS '예약 일시';
COMMENT ON COLUMN RESVE_SETLE_HIST.SETLE_PC IS '결제 가격';
COMMENT ON COLUMN RESVE_SETLE_HIST.SETLE_DT IS '결제 일시';
COMMENT ON COLUMN RESVE_SETLE_HIST.SETLE_AT IS '결제 완료 여부';
COMMENT ON COLUMN RESVE_SETLE_HIST.REFND_REQST_AT IS '환불 신청 여부';
COMMENT ON COLUMN RESVE_SETLE_HIST.PURCHS_DCSN_AT IS '구매 확정 여부';
COMMENT ON TABLE REVIEW IS '리뷰';
COMMENT ON COLUMN REVIEW.SETLE_CODE IS '결제 코드';
COMMENT ON COLUMN REVIEW.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN REVIEW.REVIEW_CN IS '리뷰 내용';
COMMENT ON COLUMN REVIEW.REVIEW_DATE IS '리뷰 일자';
COMMENT ON TABLE SELER IS '판매자';
COMMENT ON COLUMN SELER.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN SELER.SELER_SELF_INTRCN IS '판매자 자기소개';
COMMENT ON COLUMN SELER.SELER_CAREER IS '판매자 경력사항';
COMMENT ON COLUMN SELER.SELER_ACDMCR IS '판매자 학력사항';
COMMENT ON COLUMN SELER.SELER_APRSM IS '판매자 명언';
COMMENT ON COLUMN SELER.SELER_RESDNC IS '판매자 거주지역';
COMMENT ON COLUMN SELER.SELER_OCCP IS '판매자 직업';
COMMENT ON COLUMN SELER.SELER_AGE IS '판매자 연령';
COMMENT ON TABLE SELER_IMAGE IS '판매자 이미지';
COMMENT ON COLUMN SELER_IMAGE.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN SELER_IMAGE.SNO IS '등록순서';
COMMENT ON COLUMN SELER_IMAGE.IMAGE_ADRES IS '이미지 경로';
COMMENT ON TABLE SETLE IS '결제';
COMMENT ON COLUMN SETLE.SETLE_CODE IS '결제 코드';
COMMENT ON COLUMN SETLE.SETLE_PC IS '결제 가격';
COMMENT ON COLUMN SETLE.SETLE_DT IS '결제 일시';
COMMENT ON COLUMN SETLE.SETLE_AT IS '결제 완료 여부';
COMMENT ON COLUMN SETLE.REFND_REQST_AT IS '환불 신청 여부';
COMMENT ON COLUMN SETLE.PURCHS_DCSN_AT IS '구매 확정 여부';
COMMENT ON TABLE TAG IS '태그';
COMMENT ON COLUMN TAG.TAG_CODE IS '태그 코드';
COMMENT ON COLUMN TAG.TAG_NM IS '태그명';
COMMENT ON COLUMN TAG.IMAGE_ADRES IS '이미지 경로';
COMMENT ON TABLE TAG_READ_CNT IS '태그 조회수';
COMMENT ON COLUMN TAG_READ_CNT.TAG_CODE IS '태그 코드';
COMMENT ON COLUMN TAG_READ_CNT.TAG_READ_CNT IS '태그 조회수';
COMMENT ON TABLE TAG_SEARCH IS '태그 검색';
COMMENT ON COLUMN TAG_SEARCH.TAG_CODE IS '태그 코드';
COMMENT ON COLUMN TAG_SEARCH.MBER_CODE IS '회원 코드';
COMMENT ON TABLE VOCHR IS '식사권';
COMMENT ON COLUMN VOCHR.VOCHR_CODE IS '식사권 코드';
COMMENT ON COLUMN VOCHR.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN VOCHR.VOCHR_PRICE IS '식사권 가격';
COMMENT ON COLUMN VOCHR.MEAL_PREARNGE_DT IS '식사 예정 일시';
COMMENT ON COLUMN VOCHR.VOCHR_REGIST_DT IS '식사권 등록 일시';
COMMENT ON COLUMN VOCHR.MEAL_TIME IS '식사 시간';
COMMENT ON COLUMN VOCHR.DELNG_AT IS '거래 가능 여부';
COMMENT ON TABLE VOCHR_HIST IS '식사권 이력';
COMMENT ON COLUMN VOCHR_HIST.RCORD_DT IS '기록 일시';
COMMENT ON COLUMN VOCHR_HIST.HIST_SE IS '이력 구분';
COMMENT ON COLUMN VOCHR_HIST.VOCHR_CODE IS '식사권 코드';
COMMENT ON COLUMN VOCHR_HIST.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN VOCHR_HIST.VOCHR_PRICE IS '식사권 가격';
COMMENT ON COLUMN VOCHR_HIST.MEAL_PREARNGE_DT IS '식사 예정 일시';
COMMENT ON COLUMN VOCHR_HIST.VOCHR_REGIST_DT IS '식사권 등록 일시';
COMMENT ON COLUMN VOCHR_HIST.MEAL_TIME IS '식사 시간';
COMMENT ON COLUMN VOCHR_HIST.DELNG_AT IS '거래 가능 여부';
COMMENT ON TABLE WALLET IS '지갑';
COMMENT ON COLUMN WALLET.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN WALLET.COIN_CO IS '코인 수';
COMMENT ON TABLE WALLET_DTLS IS '지갑 내역';
COMMENT ON COLUMN WALLET_DTLS.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN WALLET_DTLS.RCPPAY_DT IS '입출금 일시';
COMMENT ON COLUMN WALLET_DTLS.RCPPAY_CL IS '입출금 분류';
COMMENT ON COLUMN WALLET_DTLS.RCPPAY_AMOUNT IS '입출금 금액';
COMMENT ON COLUMN WALLET_DTLS.EXCNG_COIN_CO IS '환전 코인 수';
COMMENT ON TABLE WALLET_DTLS_HIST IS '지갑내역 이력';
COMMENT ON COLUMN WALLET_DTLS_HIST.RCORD_DT IS '기록 일시';
COMMENT ON COLUMN WALLET_DTLS_HIST.HIST_SE IS '이력 구분';
COMMENT ON COLUMN WALLET_DTLS_HIST.MBER_CODE IS '회원 코드';
COMMENT ON COLUMN WALLET_DTLS_HIST.RCPPAY_DT IS '입출금 일자';
COMMENT ON COLUMN WALLET_DTLS_HIST.RCPPAY_CL IS '입출금 분류';
COMMENT ON COLUMN WALLET_DTLS_HIST.RCPPAY_AMOUNT IS '입출금 금액';
COMMENT ON COLUMN WALLET_DTLS_HIST.EXCNG_COIN_CO IS '환전 코인 수';
COMMENT ON COLUMN WALLET_DTLS_HIST.COIN_CO IS '코인 수';



